apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv-server-0
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: consul-storage-0
  local:
    path: /mnt/disk/consul-pv-server-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 192.168.52.78
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv-server-1
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: consul-storage-1
  local:
    path: /mnt/disk/consul-pv-server-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 192.168.52.79
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv-server-2
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: consul-storage-2
  local:
    path: /mnt/disk/consul-pv-server-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 192.168.52.80

